(()=>{'use strict';
const dialog=document.createElement('dialog');dialog.className='image-viewer';dialog.innerHTML='<div class="iv-panel"><div class="iv-toolbar"><span class="iv-counter"></span><button type="button" data-iv="prev">←</button><button type="button" data-iv="next">→</button><span class="iv-spacer"></span><button type="button" data-iv="out">−</button><span class="iv-zoom">100%</span><button type="button" data-iv="in">+</button><button type="button" data-iv="reset"></button><button type="button" data-iv="close">✕</button></div><div class="iv-stage"><img class="iv-image" alt="" draggable="false"></div><p class="iv-caption"></p><p class="iv-help"></p></div>';document.body.append(dialog);
const image=dialog.querySelector('.iv-image'),stage=dialog.querySelector('.iv-stage');let gallery=[],index=0,zoom=1,x=0,y=0,baseW=0,baseH=0,drag=null,returnFocus=null,previousOverflow='';const pointers=new Map();let pinch=null;
const words=()=>document.documentElement.lang==='en'?{prev:'Previous image',next:'Next image',out:'Zoom out',in:'Zoom in',reset:'Fit',close:'Close image',title:'Image viewer',help:'Drag to move · Scroll or pinch to zoom · Esc to close',open:'View image'}:{prev:'Предыдущее изображение',next:'Следующее изображение',out:'Уменьшить',in:'Увеличить',reset:'Вписать',close:'Закрыть изображение',title:'Просмотр изображения',help:'Перетаскивайте изображение · Колесо или жест для масштаба · Esc — закрыть',open:'Открыть изображение'};
function labels(){const w=words();dialog.setAttribute('aria-label',w.title);dialog.querySelector('.iv-help').textContent=w.help;dialog.querySelectorAll('[data-iv]').forEach(b=>{b.setAttribute('aria-label',w[b.dataset.iv]);b.title=w[b.dataset.iv];if(b.dataset.iv==='reset')b.textContent=w.reset;});}
function transform(){image.style.width=baseW+'px';image.style.height=baseH+'px';image.style.transform=`translate(-50%,-50%) translate(${x}px,${y}px) scale(${zoom})`;dialog.querySelector('.iv-zoom').textContent=Math.round(zoom*100)+'%';dialog.querySelector('[data-iv=out]').disabled=zoom<=.5;dialog.querySelector('[data-iv=in]').disabled=zoom>=8;}
function fit(){const rect=stage.getBoundingClientRect();if(!image.naturalWidth||!rect.width)return;const ratio=Math.min((rect.width-32)/image.naturalWidth,(rect.height-32)/image.naturalHeight,1);baseW=image.naturalWidth*ratio;baseH=image.naturalHeight*ratio;zoom=1;x=y=0;transform();}
function setZoom(value){zoom=Math.min(8,Math.max(.5,value));transform();}
function show(){const source=gallery[index];image.src=source.currentSrc||source.src;image.alt=source.alt;dialog.querySelector('.iv-caption').textContent=source.closest('figure')?.querySelector('figcaption')?.textContent||source.alt;dialog.querySelector('.iv-counter').textContent=`${index+1} / ${gallery.length}`;labels();if(image.complete)fit();}
function open(source){returnFocus=document.activeElement;gallery=[...document.querySelectorAll('main img')];index=gallery.indexOf(source);if(index<0){gallery=[source];index=0;}previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();show();dialog.querySelector('[data-iv=close]').focus();}
function close(){dialog.close();}
function move(delta){index=(index+delta+gallery.length)%gallery.length;show();}
image.addEventListener('load',fit);dialog.addEventListener('close',()=>{document.body.style.overflow=previousOverflow;pointers.clear();pinch=null;returnFocus?.focus();});
dialog.addEventListener('click',e=>{if(e.target===dialog||e.target===stage){if(!drag?.moved)close();return;}const b=e.target.closest('[data-iv]');if(!b)return;const a=b.dataset.iv;if(a==='close')close();else if(a==='in')setZoom(zoom*1.3);else if(a==='out')setZoom(zoom/1.3);else if(a==='reset')fit();else move(a==='next'?1:-1);});
dialog.addEventListener('keydown',e=>{if(['+','=','-','0','ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();if(e.key==='+'||e.key==='=')setZoom(zoom*1.3);else if(e.key==='-')setZoom(zoom/1.3);else if(e.key==='0')fit();else move(e.key==='ArrowRight'?1:-1);}});
stage.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom*(e.deltaY<0?1.12:1/1.12));},{passive:false});
stage.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});stage.setPointerCapture(e.pointerId);drag={sx:e.clientX,sy:e.clientY,x,y,moved:false};if(pointers.size===2){const p=[...pointers.values()];pinch={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),zoom};}});
stage.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinch){const p=[...pointers.values()];setZoom(pinch.zoom*Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)/pinch.distance);if(drag)drag.moved=true;}else if(drag){const dx=e.clientX-drag.sx,dy=e.clientY-drag.sy;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;x=drag.x+dx;y=drag.y+dy;transform();}});
function release(e){pointers.delete(e.pointerId);pinch=null;}stage.addEventListener('pointerup',release);stage.addEventListener('pointercancel',release);
document.addEventListener('click',e=>{if(dialog.contains(e.target))return;const button=e.target.closest('[data-view-image]');const source=button?document.querySelector(button.dataset.viewImage):e.target.closest('img');if(!source||!source.closest('main'))return;e.preventDefault();open(source);});
document.addEventListener('keydown',e=>{if(dialog.open||!['Enter',' '].includes(e.key))return;const source=e.target.matches('img')?e.target:e.target.closest('a')?.querySelector('img');if(source){e.preventDefault();open(source);}});
function enhance(){document.querySelectorAll('main img').forEach(img=>{img.classList.add('viewable-image');if(!img.closest('a')&&!img.closest('.compare-frame')){img.tabIndex=0;img.setAttribute('role','button');}const link=img.closest('a');if(link&&/\.(png|jpe?g|webp|svg)(\?|$)/i.test(link.getAttribute('href')||''))link.removeAttribute('target');});}
new MutationObserver(enhance).observe(document.querySelector('main'),{childList:true,subtree:true});new MutationObserver(labels).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});window.addEventListener('resize',()=>{if(dialog.open)fit();});enhance();labels();
})();
